export const GAME_CONSTANTS = {
  PLANE_LENGTH: 770,
  PLANE_HEIGHT: 450,
  PLANE_GAME_LENGTH: 50,

  SOLDIER_RADIUS: 7,
  SOLDIER_SELECTION_RADIUS: 15,

  EXPLOSION_RADIUS: 12,

  FUNCTION_VELOCITY: 1500, // steps per second (Java: FUNCTION_VELOCITY)
  NEXT_TURN_DELAY_MS: 3000, // delay after explosion before next turn (Java: NEXT_TURN_DELAY)

  TURN_TIME_MS: 60_000, // per-turn time limit (Java: TURN_TIME)

  FUNC_MAX_STEPS: 20000,
  FUNC_MAX_STEP_DISTANCE_SQUARED: 0.001,
  FUNC_MIN_X_STEP_DISTANCE: 0.00001,
  STEP_SIZE: 0.01,

  ANGLE_ERROR: Math.PI / 360,
  MAX_ANGLE_LOOPS: 100,

  CIRCLE_MEAN_RADIUS: 40,
  CIRCLE_STANDARD_DEVIATION: 25,
  NUM_CIRCLES_MEAN_VALUE: 15,
  NUM_CIRCLES_STANDARD_DEVIATION: 7,
} as const;

export type GameMode = "normal" | "fst_ode" | "snd_ode";
